Feature: Ingresar al modulo pagos y consultas en Prepago

  @Pre012 @PREPAGO
  Scenario: Arma tu paquete - redirección pago Tarjeta C O D
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A TARJETA CREDITO DEBITO
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO TARJETA CREDITO DEBITO


  @Pre013 @PREPAGO
  Scenario: Arma tu paquete - redirección pago PSE
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A PSE
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO PSE


  @Pre014 @PREPAGO
  Scenario: Arma tu paquete - redirección pagar con mi saldo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A PAGAR CON MI SALDO
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR PAGO CON EL SALDO


  @Pre015 @PREPAGO
  Scenario: Arma tu paquete - redirección pago Bancolombia
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A BANCOLOMBIA
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO BANCOLOMBIA


  @Pre016 @PREPAGO
  Scenario: Arma tu paquete - redirección pago Daviplata
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A DAVIPLATA
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO DAVIPLATA


  @Pre017 @PREPAGO
  Scenario: Arma tu paquete - redirección pago Codensa
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A CODENSA
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO TARJETA CREDITO DEBITO


  @Pre018 @PREPAGO
  Scenario: Arma tu paquete - redirección Otros medios de pago - TCD - Condensa - Bancolombia
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A OTROS MEDIOS DE PAGO
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   VALIDAR DIRECCIONAMIENTO OTROS MEDIOS DE PAGO


  @PRE020 @PREPAGO
  Scenario: Ingresar a recargas y paquetes y validar gestionar compras recurrentes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES EN PREPAGO
    Then  GESTIONA COMPRAS RECURRENTES


  @PRE040 @PREPAGO
  Scenario: Adquirir productos en prepago
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A ADQUIRIR PRODUCTOS
    And   SELECCIONAR LA LINEA EN PREPAGO
    And   VALIDA VERSION DE MINIPROGRAMA ADQUIRIR
    Then  VALIDA REDIRECCIONAMIENTO A PAGINA CLARO


  @Pre101 @PREPAGO
  Scenario: Arma tu paquete - redirección Otros medios de pago - PSE
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   ARMA PAQUETE PERSONALIZADO
    And   VALIDA PAQUETE SELECCIONADO
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    And   INGRESAR A OTROS MEDIOS DE PAGO
    And   VALIDAR EL RESUMEN DE LA COMPRA
    And   DIRECCIONAMIENTO OTROS MEDIOS DE PAGO PSE


  @Pre102 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes todo incluído con redes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    Then  SELECCIONAR EL TIPO DE PAQUETE TODO INCLUIDO CON REDES


  @Pre103 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes todo incluído sin redes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    Then  REALIZA LA VALIDACIÓN DE PAQUETES TODO INCLUIDO SIN REDES


  @Pre104 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de datos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    And   REALIZA LA VALIDACIÓN DE PAQUETES DE DATOS


  @PRE105 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de voz
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    Then  REALIZA RECORRIDO COMPLETO PAQUETES DE VOZ


  @PRE106 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de apps
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    Then  REALIZA RECORRIDO COMPLETO PAQUETES DE APPS



  @PRE107 @PREPAGO
  Scenario: Recargas y Paquetes - Paquetes - Recorrido paquetes relevo comunidad sorda
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONA LINEA PREPAGO
    And   VALIDAR LA MINI VERSION DE RECARGAS
    And   SELECCIONAR EL MENU PAQUETES
    Then  REALIZA RECORRIDO COMPLETO PAQUETES RELEVO COMUNIDAD SORDA
