Feature: Ingresar al módulo de Atención al cliente y soporte

  @SA054
  Scenario: Medición de red
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   INGRESA AL BOTON MEDICION DE RED
    And   VERIFICA EL MENSAJE DE AUTORIZACION EN PANTALLA
    And   ACEPTA LA AUTORIZACION DE MEDICION
    And   REALIZA TEST DE VELOCIDAD
    Then  VERIFICA LA INFORMACION EN PANTALLA Y MANEJA CONDICIONALES

  @SA055
  Scenario: Soporte Hogar
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   INGRESA A LA OPCION SOPORTE HOGAR
    Then  SELECCIONA WHATSAPP Y VALIDA REDIRECCION

  @SA056 @POSTPAGO
  Scenario: Consultar PQR
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   INGRESA A LA OPCION CONSULTAR PQR
    And   VALIDA VERSION DE MINIPROGRAMA CONSULTAR PQR
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE
    Then  VERIFICA REDIRECCION CORRECTA A PAGINA CLARO

  @SA057
  Scenario: Puntos de atención
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   INGRESA A LA OPCION PUNTOS DE ATENCION
    And   MANEJA PERMISOS DE UBICACION
    Then  VERIFICA QUE ESTE PRESENTE EL MAPA

  @SA058 @POSTPAGO
  Scenario: ¿Necesitas ayuda?
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   SELECCIONA LA OPCION NECESITAS AYUDA
    And   VALIDA VERSION DE MINIPROGRAMA NECESITAS AYUDA
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE NECESITAS AYUDA
    Then  VERIFICA REDIRECCION A CLAROBOT

  @SA080 @POSTPAGO
  Scenario: Estado de servicios técnicos Comcel
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   SELECCIONA LA OPCION ESTADO SERVICIOS TECNICOS
    And   VALIDA VERSION DE MINIPROGRAMA ESTADO SERVICIOS TECNICOS
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE SERVICIOS TECNICOS
    And   VERIFICA REDIRECCION ORDENES DE SERVICIO
    And   CONSULTA POR NUMERO DE DOCUMENTO
    And   CONSULTA POR NUMERO DE CELULAR
    Then  CONSULTA POR IMEI
