# language: es
Característica: Ingresar al módulo de Atención al cliente y soporte con lìneas prepago

  @PRE063
  Escenario: Consultar PQR Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   INGRESA A LA OPCION CONSULTAR PQR
    Y   VALIDA VERSION DE MINIPROGRAMA CONSULTAR PQR
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE CONSULTA PQR PRE
    Entonces  VERIFICA REDIRECCION CORRECTA A PAGINA CLARO

  @PRE065
  Escenario: ¿Necesitas ayuda? Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   SELECCIONA LA OPCION NECESITAS AYUDA
    Y   VALIDA VERSION DE MINIPROGRAMA NECESITAS AYUDA
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE NECESITAS AYUDA PRE
    Entonces  VERIFICA REDIRECCION A CLAROBOT


  @PRE108
  Escenario: Estado de servicios técnicos Comcel Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   SELECCIONA LA OPCION ESTADO SERVICIOS TECNICOS
    Y   VALIDA VERSION DE MINIPROGRAMA ESTADO SERVICIOS TECNICOS
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE SERVICIOS TECNICOS PRE
    Y   VERIFICA REDIRECCION ORDENES DE SERVICIO
    Y   CONSULTA POR NUMERO DE DOCUMENTO
    Y   CONSULTA POR NUMERO DE CELULAR
    Entonces  CONSULTA POR IMEI
