Feature: Ingresar al módulo de Atención al cliente y soporte con lìneas prepago

  @PRE063 @PREPAGO
  Scenario: Consultar PQR Prepago
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   INGRESA A LA OPCION CONSULTAR PQR
    And   VALIDA VERSION DE MINIPROGRAMA CONSULTAR PQR
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE CONSULTA PQR PRE
    Then  VERIFICA REDIRECCION CORRECTA A PAGINA CLARO

  @PRE065 @PREPAGO
  Scenario: ¿Necesitas ayuda? Prepago
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   SELECCIONA LA OPCION NECESITAS AYUDA
    And   VALIDA VERSION DE MINIPROGRAMA NECESITAS AYUDA
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE NECESITAS AYUDA PRE
    Then  VERIFICA REDIRECCION A CLAROBOT


  @PRE107 @PREPAGO
  Scenario: Estado de servicios técnicos Comcel Prepago
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    And   SELECCIONA LA OPCION VER MAS
    And   SELECCIONA LA OPCION ESTADO SERVICIOS TECNICOS
    And   VALIDA VERSION DE MINIPROGRAMA ESTADO SERVICIOS TECNICOS
    And   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE SERVICIOS TECNICOS PRE
    And   VERIFICA REDIRECCION ORDENES DE SERVICIO
    And   CONSULTA POR NUMERO DE DOCUMENTO
    And   CONSULTA POR NUMERO DE CELULAR
    Then  CONSULTA POR IMEI