# language: es
Característica: Ingresar al módulo de Atención al cliente y soporte

  @SA054
  Escenario: Medición de red
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   INGRESA AL BOTON MEDICION DE RED
    Y   VERIFICA EL MENSAJE DE AUTORIZACION EN PANTALLA
    Y   ACEPTA LA AUTORIZACION DE MEDICION
    Y   REALIZA TEST DE VELOCIDAD
    Entonces  VERIFICA LA INFORMACION EN PANTALLA Y MANEJA CONDICIONALES

  @SA055
  Escenario: Soporte Hogar
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   INGRESA A LA OPCION SOPORTE HOGAR
    Entonces  SELECCIONA WHATSAPP Y VALIDA REDIRECCION

  @SA056 
  Escenario: Consultar PQR
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   INGRESA A LA OPCION CONSULTAR PQR
    Y   VALIDA VERSION DE MINIPROGRAMA CONSULTAR PQR
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE
    Entonces  VERIFICA REDIRECCION CORRECTA A PAGINA CLARO

  @SA057
  Escenario: Puntos de atención
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   INGRESA A LA OPCION PUNTOS DE ATENCION
    Y   MANEJA PERMISOS DE UBICACION
    Entonces  VERIFICA QUE ESTE PRESENTE EL MAPA

  @SA058 
  Escenario: ¿Necesitas ayuda?
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   SELECCIONA LA OPCION NECESITAS AYUDA
    Y   VALIDA VERSION DE MINIPROGRAMA NECESITAS AYUDA
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE NECESITAS AYUDA
    Entonces  VERIFICA REDIRECCION A CLAROBOT

  @SA080 
  Escenario: Estado de servicios técnicos Claro
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   DESPLAZA HASTA LA OPCION ATENCION AL CLIENTE Y SOPORTE
    Y   SELECCIONA LA OPCION VER MAS
    Y   SELECCIONA LA OPCION ESTADO SERVICIOS TECNICOS
    Y   VALIDA VERSION DE MINIPROGRAMA ESTADO SERVICIOS TECNICOS
    Y   DESPLAZA HASTA LINEA Y SELECCIONA VER DETALLE SERVICIOS TECNICOS
    Y   VERIFICA REDIRECCION ORDENES DE SERVICIO
    Y   CONSULTA POR NUMERO DE DOCUMENTO
    Y   CONSULTA POR NUMERO DE CELULAR
    Entonces  CONSULTA POR IMEI
