Feature: Ingresar al módulo de entretenimiento

  @SA059
  Scenario: Ingresar a entretenimiento y validar Claro Video
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   SELECCIONA EL BOTON CLARO VIDEO
    And   VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
    Then  VALIDA REDIRECCION APP STORE CLARO VIDEO

  @SA070
  Scenario: Ingresar a entretenimiento y validar Claro Club
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   SELECCIONA EL BOTON CLARO CLUB
    And   VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
    Then  VALIDA REDIRECCION CLARO CLUB

  @SA062
  Scenario: Ingresar a entretenimiento y validar Claro Música
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   SELECCIONA EL BOTON CLARO MUSICA
    And   VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
    Then  VALIDA REDIRECCION CLARO MUSICA APP


  @SA063
  Scenario: Ingresar a entretenimiento y validar Netflix con términos y condiciones
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   SELECCIONA BOTON NETFLIX
    And   VALIDA REDIRECCIONAMIENTO NETFLIX
    And   VALIDA TERMINOS Y CONDICIONES NETFLIX
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO


  @SA066
  Scenario: Ingresar a entretenimiento y validar Disney+ plan estándar
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    #And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    #And   SELECCIONA BOTON VER MAS PLATAFORMAS
    And   SELECCIONA BOTON DISNEY PLUS
    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    And   SELECCIONA PLAN ESTANDAR DISNEY
    And   VALIDA TERMINOS Y CONDICIONES DISNEY ESTANDAR
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO

  @SA067
  Scenario: Ingresar a entretenimiento y validar Disney+ plan premium
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    #And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    #And   SELECCIONA BOTON VER MAS PLATAFORMAS
    And   SELECCIONA BOTON DISNEY PLUS
    And   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    And   SELECCIONA PLAN PREMIUM DISNEY
    And   VALIDA TERMINOS Y CONDICIONES DISNEY PREMIUM
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO

  @SA069
  Scenario: Ingresar a entretenimiento y validar Amazon Prime con términos y condiciones
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #And   VALIDA REDIRECCION A ENTRETENIMIENTO
    #And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    And   SELECCIONA BOTON AMAZON PRIME
    And   VALIDAR VERSION DE MINIPROGRAMA AMAZONPRIME
    And   SELECCIONA PLAN AMAZON PRIME
    And   VALIDA TERMINOS Y CONDICIONES AMAZON PRIME
    Then  VALIDA REDIRECCIONAMIENTO ID ClARO






















  @SA068
  Scenario: Ingresar a entretenimiento y validar HotGo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    And   SELECCIONA BOTON VER MAS PLATAFORMAS
    And   SELECCIONA BOTON HOTGO
    Then  VALIDA REDIRECCION A PAGINA HOTGO

  @SA065
  Scenario: Ingresar a entretenimiento y validar HBOmax
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    And   SELECCIONA BOTON HBOMAX
    Then  VALIDA REDIRECCION PAGINA A HBOMAX

  @SA064
  Scenario: Ingresar a entretenimiento y validar Win Play
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    And   SELECCIONA BOTON VER MAS PLATAFORMAS
    And   SELECCIONA BOTON WIN PLAY
    Then  VALIDA REDIRECCION A PAGINA WIN PLAY

  @SA060
  Scenario: Ingresar a entretenimiento y validar RED + TV en vivo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   SELECCIONA EL BOTON RED PLUS TV EN VIVO
    Then  VALIDA REDIRECCION A RED PLUS TV EN VIVO

  @SA061
  Scenario: Ingresar a entretenimiento y validar RED + NOTICIAS
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    And   VALIDA REDIRECCION A ENTRETENIMIENTO
    And   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    And   SELECCIONA BOTON VER MAS PLATAFORMAS
    And   SELECCIONA BOTON RED PLUS NOTICIAS
    And   SELECCIONA LA OPCION VER DETALLE CLARO MUSICA
    Then  VALIDA REDIRECCION RED PLUS NOTICIAS
