# language: es
Característica: Ingresar al módulo de entretenimiento

  ############################################### pospago prioridad por barra entretenimiento

  @SA059 
  Escenario: Ingresar a entretenimiento y validar Claro Video
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA EL BOTON CLARO VIDEO
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
    Entonces  VALIDA REDIRECCION APP STORE CLARO VIDEO


  @SA062 
  Escenario: Ingresar a entretenimiento y validar Claro Música
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA EL BOTON CLARO MUSICA
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
    Entonces  VALIDA REDIRECCION CLARO MUSICA APP


  @SA063 
  Escenario: Ingresar a entretenimiento y validar Netflix con términos y condiciones
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA BOTON NETFLIX
    Y   VALIDA VERSION DE MINIPROGRAMA NETFLIX
    Y   VALIDA TERMINOS Y CONDICIONES NETFLIX
    #Entonces  VALIDA REDIRECCIONAMIENTO ID ClARO


  @SA066 
  Escenario: Ingresar a entretenimiento y validar Disney+ plan estándar
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA BOTON DISNEY PLUS
    Y   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    Y   SELECCIONA PLAN ESTYAR DISNEY
    #Y   VALIDA TERMINOS Y CONDICIONES DISNEY ESTYAR
    #Entonces  VALIDA REDIRECCIONAMIENTO ID ClARO

  @SA067 
  Escenario: Ingresar a entretenimiento y validar Disney+ plan premium
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA BOTON DISNEY PLUS
    Y   VALIDAR VERSION DE MINIPROGRAMA DISNEY
    Y   SELECCIONA PLAN PREMIUM DISNEY
    Y   VALIDA TERMINOS Y CONDICIONES DISNEY PREMIUM
    Entonces  VALIDA REDIRECCIONAMIENTO ID ClARO

  @SA069
  Escenario: Ingresar a entretenimiento y validar Amazon Prime con términos y condiciones
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA BOTON AMAZON PRIME
    Y   VALIDAR VERSION DE MINIPROGRAMA AMAZONPRIME
    Y   SELECCIONA PLAN AMAZON PRIME
    Y   VALIDA TERMINOS Y CONDICIONES AMAZON PRIME
    Entonces  VALIDA REDIRECCIONAMIENTO ID ClARO


  @SA081 
  Escenario: Ingresar a entretenimiento y validar redirección a Claro Club
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA EL BOTON CLARO CLUB
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
    Entonces  VALIDA REDIRECCION CLARO CLUB


  ############################################################## pospago prioridad por tus servicios favoritos

  @SA082 
  Escenario: Validar redireccion Claro Video ingresYo por tus servicios favoritos
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
    Y   SELECCIONA EL BOTON CLARO VIDEO
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO VIDEO
    Entonces  VALIDA REDIRECCION APP STORE CLARO VIDEO

  @SA083
  Escenario: Validar redireccion Claro Musica ingresYo por tus servicios favoritos
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
    Y   SELECCIONA EL BOTON CLARO MUSICA
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO MUSICA
    Entonces  VALIDA REDIRECCION CLARO MUSICA APP


  ############################################ Claro Club por explora y compra
  @SA084
  Escenario: Explora y Compra Redirección de Claro Club
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON CUPONES EN EXPLORA Y COMPRA
    Y   VALIDA VERSION DE MINIPROGRAMA CLARO CLUB
    Entonces  VALIDA REDIRECCION CLARO CLUB

  ############################################ Entretenimiento Prepago prioridad
  @PRE079
  Escenario: Ingresar a entretenimiento y validar Claro Video Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA EL BOTON CLARO VIDEO
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO VIDEO
    Entonces  VALIDA REDIRECCION APP STORE CLARO VIDEO

  @PRE109
  Escenario: Ingresar a entretenimiento y validar Claro Club Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   SELECCIONA EL BOTON CLARO CLUB
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO CLUB
    Entonces  VALIDA REDIRECCION CLARO CLUB

  @PRE110
  Escenario: Explora y Compra Redirección de Claro Club Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON CUPONES EN EXPLORA Y COMPRA
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO CLUB
    Entonces  VALIDA REDIRECCION CLARO CLUB

  @PRE082
  Escenario: Ingresar a entretenimiento y validar Claro Música Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    #Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   SELECCIONA EL BOTON CLARO MUSICA
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO MUSICA
    Entonces  VALIDA REDIRECCION CLARO MUSICA APP

  @PRE112
  Escenario: Validar redireccion Claro Video ingresYo por tus servicios favoritos Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
    Y   SELECCIONA EL BOTON CLARO VIDEO
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO VIDEO
    Entonces  VALIDA REDIRECCION APP STORE CLARO VIDEO

  @PRE111 
  Escenario: Validar redireccion Claro Musica ingresYo por tus servicios favoritos Prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON VER MAS EN SECCION TUS SERVCICOS FAVORITOS
    Y   SELECCIONA EL BOTON CLARO MUSICA
    Y   VALIDA VERSION DE MINIPROGRAMA PRE CLARO MUSICA
    Entonces  VALIDA REDIRECCION CLARO MUSICA APP















  #******* NO ESTA DENTRO DEL CONTINUOS *************
    @SA068
  Escenario: Ingresar a entretenimiento y validar HotGo
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    Y   SELECCIONA BOTON VER MAS PLATAFORMAS
    Y   SELECCIONA BOTON HOTGO
    Entonces  VALIDA REDIRECCION A PAGINA HOTGO

  @SA065
  Escenario: Ingresar a entretenimiento y validar HBOmax
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    Y   SELECCIONA BOTON HBOMAX
    Entonces  VALIDA REDIRECCION PAGINA A HBOMAX

  @SA064
  Escenario: Ingresar a entretenimiento y validar Win Play
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    Y   SELECCIONA BOTON VER MAS PLATAFORMAS
    Y   SELECCIONA BOTON WIN PLAY
    Entonces  VALIDA REDIRECCION A PAGINA WIN PLAY

  @SA060
  Escenario: Ingresar a entretenimiento y validar RED + TV en vivo
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   SELECCIONA EL BOTON RED PLUS TV EN VIVO
    Entonces  VALIDA REDIRECCION A RED PLUS TV EN VIVO

  @SA061
  Escenario: Ingresar a entretenimiento y validar RED + NOTICIAS
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   SELECCIONA EL BOTON ENTRETENIMIENTO EN LA BARRA INFERIOR
    Y   VALIDA REDIRECCION A ENTRETENIMIENTO
    Y   DESPLAZARSE HASTA EL MODULO TUS PLATAFORMAS FAVORITAS
    Y   SELECCIONA BOTON VER MAS PLATAFORMAS
    Y   SELECCIONA BOTON RED PLUS NOTICIAS
    Y   SELECCIONA LA OPCION VER DETALLE CLARO MUSICA
    Entonces  VALIDA REDIRECCION RED PLUS NOTICIAS
