Feature: Ingresar al modulo pagos y consultas

  @SA004
  Scenario: Ingresar a paga tu factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   VALIDAR REDIRECCION BOTON PAGAR FACTURA
    Then  VALIDAR REDIRECCION DE LOS MEDIOS DE PAGO

  @SA005
  Scenario: Ingresar a paga tu factura y realizar pago parcial
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   REALIZA PAGO PARCIAL
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA006
  Scenario: Ingresar a paga tu factura y validar pagos automáticos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA PAGOS AUTOMATICOS

  @SA007
  Scenario: Ingresar a paga tu factura y validar descarga de factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  DESCARGA FACTURA

  @SA008
  Scenario: Ingresar a paga tu factura y validar envío de factura por correo electrónico
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  ENVIA FACTURA POR CORREO


  @SA009
  Scenario: Ingresar a paga tu factura y validar detalle de última facturación
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA DETALLE ULTIMA FACTURACION


  @SA0010
  Scenario: Ingresar a paga tu factura y validar historial de pagos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA HISTORIAL DE PAGOS


  @SA0011
  Scenario: Ingresar a recargas y paquetes y validar Paquetes LDI o Datos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  VALIDA PAQUETES LDI O DATOS


  @SA0013
  Scenario: Ingresar a recargas y paquetes y validar Recargas
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    And   SELECCIONA RECARGAS
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA0014
  Scenario: Ingresar a recargas y paquetes y validar gestionar compras recurrentes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  GESTIONA COMPRAS RECURRENTES

  @SA0015
  Scenario: Ingresar a Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then   VALIDA DETALLE DE TU PLAN
