Feature: Ingresar al modulo pagos y consultas

  @SA004
  Scenario: Ingresar a paga tu factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   VALIDAR REDIRECCION BOTON PAGAR FACTURA
    Then  VALIDAR REDIRECCION DE LOS MEDIOS DE PAGO

  @SA005
  Scenario: Ingresar a paga tu factura y realizar pago parcial
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   REALIZA PAGO PARCIAL
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA006
  Scenario: Ingresar a paga tu factura y validar pagos automáticos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA PAGOS AUTOMATICOS

  @SA007
  Scenario: Ingresar a paga tu factura y validar descarga de factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  DESCARGA FACTURA

  @SA008
  Scenario: Ingresar a paga tu factura y validar envío de factura por correo electrónico
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  ENVIA FACTURA POR CORREO


  @SA009
  Scenario: Ingresar a paga tu factura y validar detalle de última facturación
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA DETALLE ULTIMA FACTURACION


  @SA0010
  Scenario: Ingresar a paga tu factura y validar historial de pagos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA HISTORIAL DE PAGOS


  @SA0011
  Scenario: Ingresar a recargas y paquetes y validar Paquetes LDI o Datos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  VALIDA PAQUETES LDI O DATOS


  @SA0013
  Scenario: Ingresar a recargas y paquetes y validar Recargas
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    And   SELECCIONA RECARGAS
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA0014
  Scenario: Ingresar a recargas y paquetes y validar gestionar compras recurrentes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  GESTIONA COMPRAS RECURRENTES

  @SA0015
  Scenario: Ingresar a Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then   VALIDA DETALLE DE TU PLAN

  @SA020
  Scenario: Ingresar a gestiona tu equipo y registrar equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    Then  SELECCIONA LA OPCION REGISTRAR EQUIPO


  @SA021
  Scenario: Ingresar a gestiona tu equipo y reportar por robo o pérdida
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION REPORTAR POR ROBO O PERDIDA
    Then  CONFIRMA INGRESO A LA OPCION Y VALIDA TEXTOS DISPONIBLES

  @SA022
  Scenario: Ingresar a gestiona tu equipo y solucionar equipo con IMEI duplicado
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION SOLUCIONAR EQUIPO CON IMEI DUPLICADO
    Then  VERIFICA QUE SE MUESTREN LAS DOS OPCIONES EN PANTALLA

  @SA023
  Scenario: Ingresar a gestiona tu equipo y reconectar por robo o pérdida
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION RECONECTAR POR ROBO O PERDIDA
    Then  VALIDA TEXTO DISPONIBLE Y CIERRA MODAL

  @SA024
  Scenario: Ingresar a gestiona tu equipo y consultar equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION CONSULTAR EQUIPO
    Then  VERIFICA INFORMACION DISPONIBLE DEL EQUIPO

  @SA025
  Scenario: Ingresar a gestiona tu equipo y actualizar datos de tu equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    Then   SELECCIONA LA OPCION ACTUALIZAR DATOS DE TU EQUIPO

  @SA026
  Scenario: Ingresar a consultar consumos y validar información detallada
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO CONSULTAR CONSUMOS
    And   DESPLAZARSE HASTA EL NUMERO Y SELECCIONAR VER DETALLE
    And   ESPERA A QUE INGRESE A LA OPCION
    And   VERIFICA LOS TEXTOS DISPONIBLES
    And   SELECCIONA CONSUMO DE DATOS
    And   VALIDA LA INFORMACION DISPONIBLE DE DATOS
    And   REGRESA ATRAS Y SELECCIONA APPS SIN LIMITE DE CONSUMO
    And   VALIDA LA INFORMACION DISPONIBLE DE APPS
    And   REGRESA ATRAS Y SELECCIONA CONSUMO DE VOZ
    And   VERIFICA MENSAJE AUN NO REGISTRAS CONSUMOS VOZ
    And   REGRESA ATRAS Y SELECCIONA CONSUMO DE SMS
    And   VERIFICA MENSAJE AUN NO REGISTRAS CONSUMOS SMS
    And   REGRESA ATRAS Y SELECCIONA CONSUMO PAQUETES Y RECARGAS
    And   VERIFICA LA INFORMACION DISPONIBLE PAQUETES RECARGAS
    And   VERIFICA OPCION PAQUETES
    And   VALIDA MENSAJE AUN NO HAS ADQUIRIDO PAQUETES
    And   VERIFICA OPCION RECARGAS
    And   VALIDA MENSAJE AUN NO HAS HECHO RECARGAS
    And   VERIFICA OPCION CONSUMO DEL MES
    Then  VALIDA MENSAJE EN ESTE MES NO REGISTRAS CONSUMOS
