# language: es
Característica: Ingresar al modulo pagos y consultas en Prepago

  #@PRE012
  Escenario: Arma tu paquete - redirección pago Tarjeta C O D
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A TARJETA CREDITO DEBITO
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO TARJETA CREDITO DEBITO


  #@PRE013
  Escenario: Arma tu paquete - redirección pago PSE
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A PSE
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO PSE


  Escenario: Arma tu paquete - redirección pagar con mi saldo
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A PAGAR CON MI SALDO
    Y   VALIDAR EL RESUMEN DE LA COMPRA

  #@PRE015
  Escenario: Arma tu paquete - redirección pago Bancolombia
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A BANCOLOMBIA
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO BANCOLOMBIA


  #@PRE016
  Escenario: Arma tu paquete - redirección pago Daviplata
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A DAVIPLATA
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO DAVIPLATA



  Escenario: Arma tu paquete - redirección pago Codensa
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A CODENSA
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO TARJETA CREDITO DEBITO


  #@PRE018
  Escenario: Arma tu paquete - redirección Otros medios de pago - TCD - Condensa - Bancolombia
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A OTROS MEDIOS DE PAGO
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   VALIDAR DIRECCIONAMIENTO OTROS MEDIOS DE PAGO



  Escenario: Ingresar a recargas y paquetes y validar gestionar compras recurrentes
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   INGRESA A RECARGAS Y PAQUETES EN PREPAGO
    Entonces  GESTIONA COMPRAS RECURRENTES


  @PRE040
  Escenario: Adquirir productos en prepago
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   INGRESA A ADQUIRIR PRODUCTOS
    Y   SELECCIONAR LA LINEA EN PREPAGO
    Y   VALIDA VERSION DE MINIPROGRAMA ADQUIRIR
    Entonces  VALIDA REDIRECCIONAMIENTO A PAGINA CLARO


  #@PRE101
  Escenario: Arma tu paquete - redirección Otros medios de pago - PSE
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   ARMA PAQUETE PERSONALIZADO
    Y   VALIDA PAQUETE SELECCIONADO
    Entonces  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES
    Y   INGRESAR A OTROS MEDIOS DE PAGO
    Y   VALIDAR EL RESUMEN DE LA COMPRA
    Y   DIRECCIONAMIENTO OTROS MEDIOS DE PAGO PSE


  @PRE102
  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes todo incluído con redes
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Entonces  SELECCIONAR EL TIPO DE PAQUETE TODO INCLUIDO CON REDES


  @PRE103
  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes todo incluído sin redes
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Entonces  REALIZA LA VALIDACIÓN DE PAQUETES TODO INCLUIDO SIN REDES


  @PRE104
  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de datos
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Y   REALIZA LA VALIDACIÓN DE PAQUETES DE DATOS


  @PRE105
  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de voz
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Entonces  REALIZA RECORRIDO COMPLETO PAQUETES DE VOZ


  @PRE106
  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes de apps
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Entonces  REALIZA RECORRIDO COMPLETO PAQUETES DE APPS



  Escenario: Recargas y Paquetes - Paquetes - Recorrido paquetes relevo comunidad sorda
    Dado EL USUARIO ABRE LA SUPER APP
    Cuando  REALIZA EL INGRESO
    Y   INGRESA AL MENU PAGOS Y CONSULTAS
    Y   SELECCIONA LINEA PREPAGO
    Y   VALIDAR LA MINI VERSION DE RECARGAS
    Y   SELECCIONAR EL MENU PAQUETES
    Entonces  REALIZA RECORRIDO COMPLETO PAQUETES RELEVO COMUNIDAD SORDA
