Feature: Ingresar al modulo pagos y consultas

  @SA004 @POSTPAGO
  Scenario: Ingresar a paga tu factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   VALIDAR REDIRECCION BOTON PAGAR FACTURA
    Then  VALIDAR REDIRECCION DE LOS MEDIOS DE PAGO

  @SA005 @POSTPAGO
  Scenario: Ingresar a paga tu factura y realizar pago parcial
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    And   REALIZA PAGO PARCIAL
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA006 @POSTPAGO
  Scenario: Ingresar a paga tu factura y validar pagos automáticos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA PAGOS AUTOMATICOS

  @SA007 @POSTPAGO
  Scenario: Ingresar a paga tu factura y validar descarga de factura
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  DESCARGA FACTURA

  @SA008 @POSTPAGO
  Scenario: Ingresar a paga tu factura y validar envío de factura por correo electrónico
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  ENVIA FACTURA POR CORREO


  @SA009 @POSTPAGO
  Scenario: Ingresar a paga tu factura y validar detalle de última facturación
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA DETALLE ULTIMA FACTURACION


  @SA010 @POSTPAGO
  Scenario: Ingresar a paga tu factura y validar historial de pagos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE PAGA TU FACTURA
    Then  VALIDA HISTORIAL DE PAGOS


  @SA011
  Scenario: Ingresar a recargas y paquetes y validar Paquetes LDI
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  VALIDA PAQUETES LDI


  @SA012
  Scenario: Recargas y Paquetes - Paquetes complementarios
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  VALIDA DIRECCIONAMIENTO PAQUETES COMPLEMENTARIOS


  @SA013
  Scenario: Ingresar a recargas y paquetes y validar Recargas
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    And   SELECCIONA RECARGAS
    Then  VALIDA LA REDIRECCION A MEDIOS DE PAGO DISPONIBLES

  @SA014
  Scenario: Ingresar a recargas y paquetes y validar gestionar compras recurrentes
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  GESTIONA COMPRAS RECURRENTES

  @SA015
  Scenario: Ingresar a Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then   VALIDA DETALLE DE TU PLAN


  @SA016
  Scenario: Ingresar a Ver factura desde Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA VER FACTURA
    Then  VALIDA DIRECCIONAMIENTO PAGAR FACTURA


  @SA017 ##OJO REVISAR
  Scenario: Ingresar a Familia y amigos desde Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA FAMILIA Y AMIGOS
    And   SELECCIONA LINEA POSTPAGO
    And   VALIDA DIRECCIONAMIENTO FAMILIA Y AMIGOS
    And   INGRESA OPCION FAMILIA Y AMIGOS
    And   VALIDA EL GRUPO DE FAMILIA Y AMIGOS
    And   REGRESA ATRAS
    And   INGRESA OPCION ELEGIDOS TODO DESTINO
    And   VALIDA DIRECCIONAMIENTO ELEGIDOS TODO DESTINO
    Then  VE TERMINOS Y CONDICIONES


  @SA018
  Scenario: Ingresar a Aplicaciones elegibles - Compra de Aplicaciones - Plan que permite
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA Y VALIDA APLICACIONES ELEGIBLES
    And   INGRESA Y VALIDA COMPRAR APLICACIONES



  @SA019
  Scenario: Ingresar a Mejorar plan desde Detalle de tu plan
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA MEJORAR PLAN
    Then  VALIDA DIRECCIONAMIENTO MEJORAR PLAN

  @SA020
  Scenario: Ingresar a gestiona tu equipo y registrar equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    Then  SELECCIONA LA OPCION REGISTRAR EQUIPO


  @SA021
  Scenario: Ingresar a gestiona tu equipo y reportar por robo o pérdida
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION REPORTAR POR ROBO O PERDIDA
    Then  CONFIRMA INGRESO A LA OPCION Y VALIDA TEXTOS DISPONIBLES

  @SA022
  Scenario: Ingresar a gestiona tu equipo y solucionar equipo con IMEI duplicado
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION SOLUCIONAR EQUIPO CON IMEI DUPLICADO
    Then  VERIFICA QUE SE MUESTREN LAS DOS OPCIONES EN PANTALLA

  @SA023
  Scenario: Ingresar a gestiona tu equipo y reconectar por robo o pérdida
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION RECONECTAR POR ROBO O PERDIDA
    Then  VALIDA TEXTO DISPONIBLE Y CIERRA MODAL

  @SA024
  Scenario: Ingresar a gestiona tu equipo y consultar equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    And   SELECCIONA LA OPCION CONSULTAR EQUIPO
    Then  VERIFICA INFORMACION DISPONIBLE DEL EQUIPO

  @SA025
  Scenario: Ingresar a gestiona tu equipo y actualizar datos de tu equipo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO GESTIONA TU EQUIPO
    Then   SELECCIONA LA OPCION ACTUALIZAR DATOS DE TU EQUIPO

  @SA026
  Scenario: Ingresar a consultar consumos y validar información detallada
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MODULO CONSULTAR CONSUMOS
    And   DESPLAZARSE HASTA EL NUMERO Y SELECCIONAR VER DETALLE
    And   ESPERA A QUE INGRESE A LA OPCION
    And   VERIFICA LOS TEXTOS DISPONIBLES
    And   SELECCIONA CONSUMO DE DATOS
    And   VALIDA LA INFORMACION DISPONIBLE DE DATOS
    And   REGRESA ATRAS Y SELECCIONA APPS SIN LIMITE DE CONSUMO
    And   VALIDA LA INFORMACION DISPONIBLE DE APPS
    And   REGRESA ATRAS Y SELECCIONA CONSUMO DE VOZ
    And   VERIFICA MENSAJE AUN NO REGISTRAS CONSUMOS VOZ
    And   REGRESA ATRAS Y SELECCIONA CONSUMO DE SMS
    And   VERIFICA MENSAJE AUN NO REGISTRAS CONSUMOS SMS
    And   REGRESA ATRAS Y SELECCIONA CONSUMO PAQUETES Y RECARGAS
    And   VERIFICA LA INFORMACION DISPONIBLE PAQUETES RECARGAS
    And   VERIFICA OPCION PAQUETES
    And   VALIDA MENSAJE AUN NO HAS ADQUIRIDO PAQUETES
    And   VERIFICA OPCION RECARGAS
    And   VALIDA MENSAJE AUN NO HAS HECHO RECARGAS
    And   VERIFICA OPCION CONSUMO DEL MES
    Then  VALIDA MENSAJE EN ESTE MES NO REGISTRAS CONSUMOS
    Then  VALIDA DETALLE DE TU PLAN
    And   VALIDA DESCRIPCION DEL PLAN

  @SA027
  Scenario: Familia y amigos - Agregar, eliminar y desactivar servicio
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA FAMILIA Y AMIGOS
    And   SELECCIONA LINEA POSTPAGO
    And   VALIDA DIRECCIONAMIENTO FAMILIA Y AMIGOS
    And   INGRESA OPCION FAMILIA Y AMIGOS

  @SA028
  Scenario: Validar direccionamiento Roaming
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO A ROAMING


  @SA029
  Scenario: Estado de portabilidad desde Pagos y consultas
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A PORTABILIDAD
    And   VALIDA VERSION DE MINIPROGRAMA PORTABILIDAD
    Then  VALIDA ESTADO DE PORTABILIDAD Y REDIRECCION


  @SA030
  Scenario: Envío de SIM Card desde Portabilidad
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A PORTABILIDAD
    And   VALIDA VERSION DE MINIPROGRAMA PORTABILIDAD
    Then  VALIDA ENVIO DE SIM CARD Y REDIRECCION


  @SA031
  Scenario: Portabilidad prepago desde Portabilidad
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A PORTABILIDAD
    And   VALIDA VERSION DE MINIPROGRAMA PORTABILIDAD
    Then  VALIDA PORTABILIDAD PREPAGO Y REDIRECCION

  @SA032
  Scenario: Portabilidad postpago desde Portabilidad
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A PORTABILIDAD
    And   VALIDA VERSION DE MINIPROGRAMA PORTABILIDAD
    Then  VALIDA PORTABILIDAD POSTPAGO Y REDIRECCION


  @SA033
  Scenario: Adquirir productos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A ADQUIRIR PRODUCTOS
    And   SELECCIONA LINEA POSTPAGO
    And   VALIDA VERSION DE MINIPROGRAMA ADQUIRIR
    Then  VALIDA REDIRECCIONAMIENTO A PAGINA CLARO


  @SA034
  Scenario: eSIM Claro
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA A ESIM CLARO
    And   SELECCIONA LINEA POSTPAGO eSIM
    And   PRESIONA BOTON SIGUIENTE
    And   VALIDA VERSION DE MINIPROGRAMA ESIM
    Then  VALIDA DIRECCIONAMIENTO OPCIONES ESIM


  @SA035
  Scenario: Certificación cuenta al día
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  GESTIONA CERTIFICACION CUENTA AL DIA


  @SA036
  Scenario: Vehículo conectado
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO VEHICULO CONECTADO


  @SA037
  Scenario: Pagos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO CORRECTO PAGOS


  @SA038
  Scenario: Legalización de líneas
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO CORRECTO LEGALIZACION


  @SA039
  Scenario: Beneficios
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO CORRECTO BENEFICIOS


  @SA070
  Scenario: Ingresar a Paquetes adicionales - plan que si tiene
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA PAQUETES ADICIONALES
    Then  VALIDA DIRECCIONAMIENTO PAQUETES ADICIONALES


  @SA071
  Scenario: Ingresar a Administrar roaming - servicio NO activo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA ADMINISTRAR ROAMING
    Then  VALIDA DIRECCIONAMIENTO ROAMING


  @SA072
  Scenario: Ingresar a Adelanta tu saldo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   HACE CLIC EN ADELANTA TU SALDO
    And   SELECCIONA LINEA POSTPAGO
    And   VALIDA DIRECCIONAMIENTO CORRECTO
    Then  VERIFICA POPUP ADELANTO


  @SA073
  Scenario: Ingresar a Agendar turnos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    Then  VALIDA DIRECCIONAMIENTO AGENDAR TURNOS


  @SA074
  Scenario: Ingresar a recargas y paquetes y validar Paquetes de Datos
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   INGRESA AL PORTAL DE RECARGAS Y PAQUETES
    Then  VALIDA PAQUETES DE DATOS


  @SA075
  Scenario: Ingresar a Aplicaciones elegibles - Compra de Aplicaciones - Plan que NO permite
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN PARA LINEA QUE NO PERMITE COMPRAR APLICACIONES
    And   INGRESA Y VALIDA APLICACIONES ELEGIBLES
    Then  INGRESA Y VALIDA COMPRAR APLICACIONES NO PERMITIDO


  @SA076
  Scenario: Ingresar a Aplicaciones elegibles - Administra Aplicaciones - Plan que permite
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   SELECCIONAR LINEA POSTPAGO QUE PERMITA ADMINISTRAR APPS
    And   INGRESA Y VALIDA APLICACIONES ELEGIBLES
    Then  ADMINISTRAR Y VALIDAR APLICACIONES INCLUIDAS


  @SA077
  Scenario: Ingresar a Aplicaciones elegibles - Administra Aplicaciones - Plan que NO permite
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN
    And   INGRESA Y VALIDA APLICACIONES ELEGIBLES
    Then  ADMINISTRAR Y VALIDAR APLICACIONES NO PERMITIDO


  @SA078
  Scenario: Ingresar a Paquetes Adicionales - No tiene paquetes - popup
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN LINEA ESPECIFICA
    And   INGRESA PAQUETES ADICIONALES
    Then  VALIDA POPUP NO TIENE PAQUETES


  @SA079
  Scenario: Ingresar a Administrar roaming - servicio activo
    Given EL USUARIO ABRE LA SUPER APP
    When  REALIZA EL INGRESO
    And   VERIFICA VERSION DE LA SUPER APP
    And   INGRESA AL MENU PAGOS Y CONSULTAS
    And   VALIDA DETALLE DE TU PLAN PARA LINEA QUE NO PERMITE COMPRAR APLICACIONES
    And   INGRESA ADMINISTRAR ROAMING SERVICIO ACTIVO
    Then  VALIDA DIRECCIONAMIENTO ROAMING
    Then  VALIDA VIGENCIA Y PLANES ROAMING



  @Solo_Nuevos_Pasos
  Scenario: Validar solo Aplicaciones elegibles (desde detalle ya cargado)
    Given EL USUARIO ABRE LA SUPER APP
    And   INGRESA MEJORAR PLAN
    Then  VALIDA DIRECCIONAMIENTO MEJORAR PLAN
